version: '3.2'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      MACHINE_NAME: api
      CRYPT_METHOD: rsa1024
      API_HOST: 0.0.0.0
      API_PORT: 80
      MODE: api
      GIN_MODE: release
  requester:
    build: .
    environment:
      MACHINE_NAME: requester
      CRYPT_METHOD: rsa1024
      MODE: requester
      POSTGRES_URI: "user=postgres dbname=postgres host=db port=5432 sslmode=disable password=admin"
      TARGET_ADDRESS: http://api:80/token
      REQUEST_TIMES: 1
      mem_limit: 1000m
    volumes:
      - ./roles:/tokens-overhead/roles
  once-requester:
    build: .
    environment:
      MACHINE_NAME: requester
      CRYPT_METHOD: rsa1024
      MODE: unique
      TARGET_ADDRESS: http://34.125.39.144:80/token
      REQUEST_TIMES: 1
      NUM_ROLES: 370
      mem_limit: 1000m
    volumes:
      - ./roles:/tokens-overhead/roles
  nginx:
    image: nginx:1.20.2-alpine
    restart: unless-stopped
    volumes:
      - ./_infra/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"

volumes:
  postgresql-data:
    driver: local