version: '3.2'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      MACHINE_NAME: api
      CRYPT_METHOD: rsa1024
      API_HOST: 0.0.0.0
      API_PORT: 80
      MODE: api
    ports:
      - 80:80
  requester:
    build: .
    environment:
      MACHINE_NAME: requester
      CRYPT_METHOD: rsa1024
      MODE: requester
      POSTGRES_URI: "user=postgres dbname=postgres host=db port=5432 sslmode=disable password=admin"
      TARGET_ADDRESS: http://api:80/token
      REQUEST_TIMES: 1
    depends_on:
      - db
volumes:
  postgresql-data:
    driver: local